apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage-lab
  labels:
    type: local
  namespace: labwordpress
spec:
  #storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: labwordpress
    name: pvc-wordpress
  hostPath:
    path: /home/wordpress-persistent-storage-lab
    #type: DirectoryOrCreate